controllers/OrderController.php
<?php

namespace app\controllers;

use app\models\Condition;
use app\models\search\ComplaintSearch;
use Mpdf\HTMLParserMode;
use Mpdf\Mpdf;
use Yii;
use app\models\Order;
use app\models\search\OrderSearch;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;

        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['<>', 'status', Order::STATUS_CANCEL]);

        if ($request->get('append')) {
            $append = '(' . $request->get('append') . ')';
        } else {
            $append = '';
        }

        Url::remember();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'append' => $append,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Order #" . $id,
                'content' => $this->renderAjax('view', [
                    'model' => $this->findModel($id),
                ]),
                'footer' => Html::button('Закрыть',
                        ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a('Редактировать', ['update', 'id' => $id],
                        ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Order model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();
        $model->status = $model::STATUS_NEW;

        if (!$model->save()) {
            Yii::error($model->errors, '_error');
        }

        return $this->redirect(['/order/update', 'id' => $model->id]);
    }

    /**
     * Updates an existing Order model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        $condition_model = $model->condition;

        if (!$condition_model) {
            $condition_model = new Condition();
        }
        $complaintSearchModel = new ComplaintSearch();
        $complaintDataProvider = $complaintSearchModel->search(Yii::$app->request->queryParams);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Заявка №" . $id,
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                        'complaintSearchModel' => $complaintSearchModel,
                        'complaintDataProvider' => $complaintDataProvider,
                        'condition_model' => $condition_model,
                    ]),
                    'footer' => Html::button('Закрыть',
                            ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else {
                if ($model->load($request->post())) {
                    if ($model->apparatus_client_id && $model->testOfRepeat()) {
                        $model->is_repeat = 1;
                    }

                    if (!$model->save()) {
                        Yii::error($model->errors, '_error');
                    }
                    $condition_model->load($request->post());
                    $condition_model->order_id = $model->id;
                    $condition_model->save();

                    return [
                        'forceReload' => '#crud-datatable-pjax',
                        'title' => "Order #" . $id,
                        'content' => $this->renderAjax('view', [
                            'model' => $model,
                            'condition_model' => $condition_model,
                            'complaintSearchModel' => $complaintSearchModel,
                            'complaintDataProvider' => $complaintDataProvider,
                        ]),
                        'footer' => Html::button('Закрыть',
                                ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                            Html::a('Редактировать', ['update', 'id' => $id],
                                ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
                    ];
                } else {
                    return [
                        'title' => "Update Order #" . $id,
                        'content' => $this->renderAjax('update', [
                            'model' => $model,
                            'condition_model' => $condition_model,
                            'complaintSearchModel' => $complaintSearchModel,
                            'complaintDataProvider' => $complaintDataProvider,
                        ]),
                        'footer' => Html::button('Закрыть',
                                ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                            Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                    ];
                }
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post())) {
                if ($model->apparatus_client_id && $model->testOfRepeat()) {
                    $model->is_repeat = 1;
                }

                if (!$model->save()) {
                    Yii::error($model->errors, '_error');
                }

                $condition_model->load($request->post());
                $condition_model->order_id = $model->id;
                $condition_model->save();

                return $this->redirect([
                    '/order',
                    'OrderSearch[status]' => $model::STATUS_CURRENT,
                    'append' => 'Текущие'
                ]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                    'condition_model' => $condition_model,
                    'complaintSearchModel' => $complaintSearchModel,
                    'complaintDataProvider' => $complaintDataProvider,
                ]);
            }
        }
    }

    /**
     * Delete an existing Order model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
//        $this->findModel($id)->delete();
        $order = $this->findModel($id);
        $order->status = $order::STATUS_CANCEL;
        $order->save(false);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose' => true, 'forceReload' => '#crud-datatable-pjax'];
        } else {
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

    /**
     * Delete multiple existing Order model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @return mixed
     * @throws NotFoundHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionBulkDelete()
    {
        $request = Yii::$app->request;
        $pks = explode(',', $request->post('pks')); // Array or selected records primary keys
        foreach ($pks as $pk) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if ($request->isAjax) {
            /*

views/order/_close_columns.php
<?php

use app\models\constants\UsersConstants;
use app\models\Order;
use yii\helpers\Html;
use yii\helpers\Url;

return [
//    [
//        'class' => 'kartik\grid\CheckboxColumn',
//        'width' => '20px',
//    ],
//    [
//        'class' => 'kartik\grid\SerialColumn',
//        'width' => '30px',
//    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'id',
        'width' => '30px',
        'vAlign' => 'middle',
        'hAlign' => 'center',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'created_at',
        'header' => 'Дата <br> создания',
        'format' => 'datetime',
        'vAlign' => 'middle',
        'hAlign' => 'center',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'done_at',
        'header' => 'Дата <br> закрытия',
        'format' => 'date',
        'vAlign' => 'middle',
        'hAlign' => 'center',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'header' => 'Клиент',
        'attribute' => 'client_name',
        'content' => function (Order $model) {
            return $model->client ? $model->client->official_name : '';
        },
        'label' => 'Клиент',
        'vAlign' => 'middle',
        'contentOptions' => [
            'style' => 'min-width: 200px'
        ]
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'counter_1',
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'counter_2',
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'counter_3',
//    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'photos',
//    ],

    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'status',
    // ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'apparatus_name',
        'header' => 'Аппарат',
        'content' => function (Order $model) {
            return $model->apparatusToClient ? $model->apparatusToClient->apparatus->getApparatusFullName() : '';
        },
        'vAlign' => 'middle',
        'contentOptions' => [
            'style' => 'min-width: 200px'
        ],
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'serial_number',
        'header' => 'Серийный<br>номер',
        'content' => function (Order $model) {
            return $model->apparatusToClient ? $model->apparatusToClient->serial_number : '';
        },
        'vAlign' => 'middle',
        'hAlign' => 'center',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'service_type',
        'header' => 'Тип услуг',
        'filter' => (new Order())->getServiceTypeList(),
        'content' => function (Order $model) {
            return $model->serviceTypeLabel;
        },
        'vAlign' => 'middle',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'work_type',
        'header' => 'Тип работ',
        'filter' => (new Order())->getTypeWorkList(),
        'content' => function (Order $model) {
            return $model->workTypeLabel;
        },
        'vAlign' => 'middle',
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'account_number',
        'header' => 'Номер <br> счета',
        'vAlign' => 'middle',
        'hAlign' => 'center',
    ],

    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'parent_order_id',
    // ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'total_time',
        'header' => 'Затраченное <br> время (час.)',
        'vAlign' => 'middle',
        'hAlign' => 'center',
    ],

    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'manager_id',
    // ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'engineer_fio',
        'header' => 'Инженер',
        'content' => function (Order $model) {
            return $model->engineer ? $model->engineer->fio : null;
        },
        'vAlign' => 'middle',
    ],
    // [
    // 'class'=>'\kartik\grid\DataColumn',
    // 'attribute'=>'is_repeat',
    // ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'template' => '{get-sl}&nbsp;&nbsp;{copy-order}&nbsp;&nbsp;{view}&nbsp;&nbsp;{finish}&nbsp;&nbsp;{update}&nbsp;&nbsp;{delete}',
        'vAlign' => 'middle',
//        'width' => '150px',
        'urlCreator' => function ($action, $model, $key, $index) {
            return Url::to([$action, 'id' => $key]);
        },
        'buttons' => [
            'get-sl' => function ($action, Order $model) {
                if ($model->status != $model::STATUS_DONE && $model->status != $model::STATUS_CANCEL) {
                    return Html::a('<span class="glyphicon glyphicon-print"></span>', [$action], [
                        'title' => 'Распечатать сервисный лист',
                        'target' => '_blank',
                        'data-toggle' => 'tooltip',
                        'data-pjax' => 0,
                    ]);
                }
                return null;
            },
            'copy-order' => function ($action, Order $model) {
                return Html::a('<span class="glyphicon glyphicon-copy"></span>', [$action], [
                    'title' => 'Создать заявку на основании текущей заявки',
                    'target' => '_blank',
                    'data-toggle' => 'tooltip',
                    'data-pjax' => 0,
                ]);
            },
            'finish' => function ($action, Order $model) {
                if ($model->status == $model::STATUS_WORK) {
                    return Html::a('<span class="glyphicon glyphicon-saved"></span>', [$action], [
                        'title' => 'Завершить заявку',
                        'style' => 'color: green',
                        'data-toggle' => 'tooltip',
                        'role' => 'modal-remote',
                        'data-pjax' => 1,
                    ]);
                }
                return null;
            },
            'update' => function ($action, Order $model) {
                if ($model->status == $model::STATUS_NEW || UsersConstants::isSuperAdmin()) {
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', [$action], [
                        'title' => 'Редактировать',
                        'data-toggle' => 'tooltip',
                        'data-pjax' => 0,
                    ]);
                }
                return null;
            },

            'delete' => function ($action, Order $model) {
                if ($model->status == $model::STATUS_NEW || $model->status == $model::STATUS_WORK) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', [$action], [
                        'role' => 'modal-remote',
                        'title' => 'Отменить заявку',
                        'style' => 'color: red',
                        'data-confirm' => false,
                        'data-method' => false,// for overide yii data api
                        'data-request-method' => 'post',
                        'data-toggle' => 'tooltip',
                        'data-confirm-title' => 'Вы уверены?',
                        'data-confirm-message' => 'Подтвердите отмену заявки',
                        'data-confirm-ok' => 'Отменить заявку',
                        'data-confirm-cancel' => 'Закрыть окно',
                    ]);
                }
                return null;
            },

        ],
        'viewOptions' => ['title' => 'Просмотр', 'data-toggle' => 'tooltip'],
        'updateOptions' => ['title' => 'Редактирование', 'data-toggle' => 'tooltip'],
        'deleteOptions' => [
            'role' => 'modal-remote',
            'style' => 'color: red',
            'title' => 'Отменить заявку',
            'data-confirm' => false,
            'data-method' => false,// for overide yii data api
            'data-request-method' => 'post',
            'data-toggle' => 'tooltip',
            'data-confirm-title' => 'Вы уверены?',
            'data-confirm-message' => 'Подтвердите отмену заявки',
            'data-confirm-ok' => 'Отменить заявку',
            'data-confirm-cancel' => 'Закрыть окно',
        ],
        'contentOptions' => [
            'style' => 'min-width: 150px;'
        ]
    ],

];   

views/order/_form.php
<?php

use app\models\ApparatusToClient;
use app\models\Client;
use app\models\Users;
use johnitvn\ajaxcrud\CrudAsset;
use kartik\select2\Select2;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $condition_model \app\models\Condition */
/* @var $form yii\widgets\ActiveForm */
/* @var $complaintSearchModel \app\models\search\ComplaintSearch */
/* @var $complaintDataProvider \yii\data\ActiveDataProvider */

CrudAsset::register($this);

?>

<?php Pjax::begin(['id' => 'order-pjax-container', 'enablePushState' => false]) ?>

<?php
    echo "<h4 class='text-right'>Создание заявки</h4>";
?>
    <div class="container order-container">
        <div class="order-form">

            <?php $form = ActiveForm::begin(); ?>
            <div class="row">
                <div class="btn-group">
                    <?= \yii\helpers\Html::a('<span class="fa fa-arrow-left"></span>&nbsp;Назад',
                        Yii::$app->request->referrer, [
                            'class' => 'btn btn-info',
                            'style' => 'margin-bottom: 2rem;'
                        ]) ?>
                    <?= Html::submitButton('Сохранить заявку',
                        ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                </div>
            </div>
            <div class="row">
                <?php if ($model->status == $model::STATUS_WORK || $model->status == $model::STATUS_DONE): ?>

                    <div class="col-sm-12">
                        <?= $form->field($condition_model,
                            'description')->textarea(['rows' => 3])->label('Текущее состояние аппарата') ?>
                    </div>
                    <div class="col-sm-4">
                        <?= $form->field($model, 'total_time')->textInput() ?>
                    </div>
                    <div class="col-sm-4">
                        <?= $form->field($model, 'done_at')->input('date', [
                            'value' => $model->done_at ? explode(' ', $model->done_at)[0] : '',
                        ]) ?>
                    </div>
                    <div class="col-sm-4">
                        <?= $form->field($model, 'account_number')->textInput(['maxlength' => true]) ?>
                    </div>
                    <div class="col-sm-12">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                Выполненные работы
                                <?= Html::a('<span class="fa fa-plus"></span> Добавить',
                                    ['/work/create', 'id' => $model->id], [
                                        'role' => 'modal-remote',
                                        'class' => 'btn btn-default btn-xs pull-right',
                                        'style' => 'margin-bottom: 1rem;'
                                    ]) ?>
                            </div>
                            <div class="panel-body">
                                <?php Pjax::begin(['id' => 'work-pjax-container', 'enablePushState' => false]) ?>
                                <?= $this->render('@app/views/work/list', [
                                    'model' => $model,
                                ]) ?>
                                <?php Pjax::end() ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                Установленные ЗиП
                                <?= Html::a('<span class="fa fa-plus"></span> Добавить',
                                    ['/spta/create', 'id' => $model->id], [
                                        'role' => 'modal-remote',
                                        'class' => 'btn btn-default btn-xs pull-right',
                                        'style' => 'margin-bottom: 1rem;'
                                    ]) ?>
                            </div>
                            <div class="panel-body">
                                <?php Pjax::begin(['id' => 'spta-pjax-container', 'enablePushState' => false]) ?>
                                <?= $this->render('@app/views/spta/list', [
                                    'model' => $model,
                                ]) ?>
                                <?php Pjax::end() ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <!--Клиент-->
            <div class="row" style="display: flex; align-items: center;">
                <div class="col-sm-11">
                    <?php
                    try {
                        echo $form->field($model, 'client_id')->widget(Select2::class, [
                            'data' => (new Client)->getList(),
                            'options' => [
                                'id' => 'order-client',
                                'prompt' => 'Выберите заказчика'
                            ]
                        ])->label('Наименование заказчика');
                    } catch (Exception $e) {
                        echo $e->getMessage();
                    } ?>
                </div>
                <div class="col-sm-1">
                    <?= Html::a('<span class="fa fa-plus"></span>', ['/client/create', 'caller' => '/order/create'], [
                        'class' => 'btn btn-default btn-block',
                        'role' => 'modal-remote'
                    ]) ?>
                </div>
            </div>
            <!--Аппарат-->
            <div class="row" style="display: flex; align-items: center;">
                <div class="col-sm-10">
                    <?php Pjax::begin(['id' => 'apparatus-client-container']) ?>
                    <?php
                    try {
                        echo $form->field($model, 'apparatus_client_id')->widget(Select2::class, [
                            'data' => (new ApparatusToClient())->getApparatusListForClient($model->client_id),
                            'options' => [
                                'id' => 'apparatus-client',
                                'prompt' => 'Выберите аппарат',
                            ]
                        ]);
                    } catch (Exception $e) {
                        echo $e->getMessage();
                    } ?>
                    <?php Pjax::end() ?>
                </div>
                <div class="col-sm-2 btn-group btn-group-justified" role="group" style="max-width: 200px;">
                    <?= Html::a('<span class="fa fa-plus"></span>',
                        [
                            '/apparatus-to-client/create',
                            'caller' => '/order/update?id=' . $model->id,
                            'id' => $model->client_id,
                            'pjaxReloadContainer' => '#apparatus-client-container',
                        ], [
                            'class' => 'btn btn-default',
                            'role' => 'modal-remote',
                            'id' => 'add-apparatus-btn',
                            'style' => $model->client_id ? '' : 'display:none',
                            'title' => 'Добавить аппарат клиенту'
                        ]) ?>
                    <?= Html::a('<span class="fa fa-plus-square"></span>',
                        ['/apparatus/create', 'caller' => '/order/update?id=' . $model->id], [
                            'class' => 'btn btn-default',
                            'role' => 'modal-remote',
                            'id' => 'add-apparatus-model-btn',
//                            'style' => 'display:none;',
                            'title' => 'Добавить модель аппарата'
                        ]) ?>
                </div>
            </div>
            <!--Счетчики-->
            <div class="row">
                <div class="col-sm-4">
                    <?= $form->field($model, 'counter_1')->textInput() ?>
                </div>
                <div class="col-sm-4">
                    <?= $form->field($model, 'counter_2')->textInput() ?>
                </div>
                <div class="col-sm-4">
                    <?= $form->field($model, 'counter_3')->textInput() ?>
                </div>
            </div>
            <!--Инженер-->
            <div class="row">
                <div class="col-sm-12">
                    <?= $form->field($model, 'engineer_id')->dropDownList((new Users)->getEngineerList(),
                        ['prompt' => 'Выберите сотрудника']) ?>
                </div>
            </div>
            <!--Тип услуг и работ-->
            <div class="row" style="display: flex; align-items: center;">

                <div class="col-sm-4">
                    <?= $form->field($model, 'service_type')->dropDownList($model->getServiceTypeList()) ?>
                </div>
                <div class="col-sm-4">
                    <?= $form->field($model, 'work_type')->dropDownList($model->getTypeWorkList()) ?>
                </div>
                <?php if (count($model->complaints) < 3): ?>
                    <div class="col-sm-4">
                        <?= Html::a('Добавить жалобу', ['/complaint/create', 'id' => $model->id], [
                            'class' => 'btn btn-default btn-block',
                            'role' => 'modal-remote',
                        ]) ?>
                    </div>
                <?php endif; ?>
            </div>
            <!--Жалобы-->
            <div class="row">
                <div class="col-sm-12">
                    <div id="complaint-list">
                        <?php Pjax::begin(['id' => 'complaint-pjax-container', 'enablePushState' => false]) ?>
                        <?= $this->render('@app/views/complaint/list', ['model' => $model,]) ?>
                        <?php Pjax::end() ?>
                    </div>
                </div>
            </div>

            <?php if (\app\models\constants\UsersConstants::isSuperAdmin()): ?>
                <?= $form->field($model, 'status')->dropDownList($model->getStatusList()) ?>
            <?php else: ?>
                <?= $form->field($model, 'status')->hiddenInput()->label(false) ?>
            <?php endif; ?>

            <?= $form->field($model, 'parent_order_id')->hiddenInput()->label(false) ?>

            <?= $form->field($model, 'manager_id')->hiddenInput()->label(false) ?>

            <?= $form->field($model, 'is_repeat')->hiddenInput()->label(false) ?>

            <?= $form->field($model, 'created_at')->hiddenInput()->label(false) ?>

            <div class="btn-group">
                <?= \yii\helpers\Html::a('<span class="fa fa-arrow-left"></span>&nbsp;Назад',
                    Yii::$app->request->referrer, [
                        'class' => 'btn btn-info',
                        'style' => 'margin-bottom: 2rem;'
                    ]) ?>
                <?= Html::submitButton('Сохранить заявку',
                    ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

<?php Pjax::end(); ?>

<?php
$script = <<<JS
$(document).ready(function() {
    $(document).on('change','#order-client', function() {
        var client_id = $(this).val();
        var add_apparatus_btn = $('#add-apparatus-btn');
        var apparatus_dropdown = $('#apparatus-client');
        
        add_apparatus_btn.attr('href', '/apparatus-to-client/create?id=' + client_id + '&caller=/order/update?id={$model->id}&pjaxReloadContainer=apparatus-client-container');
        add_apparatus_btn.show();
        
        $('#add-apparatus-model-btn').show();
         $.get(
            '/apparatus-to-client/get-apparatus-for-client',
            {id:client_id},
            function(res) {
                if (res.success === 1){
                    apparatus_dropdown.html(res.data)
                }
            }
        );
         
        $.post(
            '/order/set-client',
            {
                order_id:{$model->id},
                client_id:client_id
            }
        );
        
       
    });
});
JS;

$this->registerJs($script);

views/order/create.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Order */

?>
<div class="order-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/order/update.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $condition_model app\models\Condition */
/* @var $complaintSearchModel \app\models\search\ComplaintSearch */
/* @var $complaintDataProvider \yii\data\ActiveDataProvider */
?>
<div class="order-update">

    <?= $this->render('_form', [
        'model' => $model,
        'condition_model' => $condition_model,
        'complaintSearchModel' => $complaintSearchModel,
        'complaintDataProvider' => $complaintDataProvider,
    ]) ?>

</div>